### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by ajsb85** [dt/ghlink#1]
Hi @dt 

I am debugging my extension and I can see this error message in the console.

`Activating extension `dt.ghlink` failed: Path must be a string. Received undefined.`

![image](https://cloud.githubusercontent.com/assets/663460/22071285/f1ccf41a-dd9e-11e6-82bf-ba91562b51c7.png)

**Comment by dt** [comment]
Thanks for the report!

I haven't seen this locally, but the code itself is only a handful of lines so I read though to see if I could guess where it was happening. My working theory is that I suspect it might be [this call](https://github.com/dt/ghlink/blob/710dcbc/src/extension.ts#L38) to `path.join` where it passes it `vscode.workspace.rootPath`, which can be `undefined` if you don't have a folder open?

I just pushed 0.0.5 to wrap that block in an `if` which might fix it, though since it wasn't reproducing for me, that's more of a speculative fix.

**Comment by ajsb85** [comment]
Hi @dt. It's works! 

Thank you.
